FROM ghcr.io/mlflow/mlflow:v3.4.0

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && \
    unzip -q /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/aws /tmp/awscliv2.zip

RUN pip install --no-cache-dir boto3

USER 1000
WORKDIR /home/mlflow

RUN mkdir -p /mlflow/db

EXPOSE 5000