version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: "sqlite:////mlflow/db/mlflow.db"
      MLFLOW_ARTIFACT_URI: "${MLFLOW_ARTIFACT_URI}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    volumes:
      - mlflow_db:/mlflow/db
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:////mlflow/db/mlflow.db
        --default-artifact-root ${MLFLOW_ARTIFACT_URI}

volumes:
  mlflow_db: